"""'21'

Revision ID: 1f98620683cf
Revises: None
Create Date: 2016-09-04 21:29:17.379000

"""

# revision identifiers, used by Alembic.
revision = '1f98620683cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('url_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tags_url_name'), 'tags', ['url_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_url_name'), table_name='tags')
    op.drop_column('tags', 'url_name')
    ### end Alembic commands ###
